dataset_path: seed_datasets/molpuzzle/meta_data.json
generator_type: benchmark
generator_config:
  prompt_templates:
    type_cls:
      template: |
        Identify the type of the given spectrum image.

        Please answer in the following JSON format:
        {{
          "question": "Your generated question here",
          "choices": ["choice1", "choice2", "choice3", "choice4", "choice5"],
          "answer": "the correct answer"
        }}

        Example:
        {{
          "question": "What type of spectrum is shown in this image?",
          "choices": ["Infrared Spectrum (IR)", "Proton Nuclear Magnetic Resonance (H-NMR)", "Carbon Nuclear Magnetic Resonance (C-NMR)", "Mass Spectrometry (MS)", "Raman Spectrum"],
          "answer": "Infrared Spectrum (IR)"
        }}
      num_choices: 5
    quality_eval:
      template: |
        Evaluate the signal quality of this spectrum image.

        Please answer in the following JSON format:
        {{
          "question": "Your generated question here",
          "choices": ["choice1", "choice2", "choice3", "choice4"],
          "answer": "the correct answer"
        }}

        Example:
        {{
          "question": "Does this spectrum show obvious signal quality issues?",
          "choices": ["Yes, obvious quality issues", "No, the signal is very clear", "Localized noise", "Very low noise, negligible"],
          "answer": "No, the signal is very clear"
        }}
      num_choices: 4
  question_types: ["type_cls", "quality_eval"]
model_type: internvl
model_config:
  api_key: ${INTERNVL_API_KEY}
  base_url: ${INTERNVL_BASE_URL}
  model_name: ${INTERNVL_MODEL_NAME}
  max_seq_len: 4096
num_samples: 30
output_path: output/benchmark.json
verbose: true
max_retries: 3 