dataset_path: seed_datasets/molpuzzle/meta_data.json
generator_type: benchmark
generator_config:
  prompt_templates:
    type_cls:
      template: |
        You are given the following spectra for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for the following task, and generate a question, choices, and answer based on it.
        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "IR",
          "question": "What type of spectrum is this?",
          "choices": ["Infrared Spectrum (IR)", "Proton Nuclear Magnetic Resonance (H-NMR)", "Mass Spectrometry (MS)", "Raman Spectrum"],
          "answer": "Infrared Spectrum (IR)"
        }}

        Example:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "What type of spectrum is this?",
          "choices": ["Infrared Spectrum (IR)", "Proton Nuclear Magnetic Resonance (H-NMR)", "Mass Spectrometry (MS)", "Raman Spectrum"],
          "answer": "Proton Nuclear Magnetic Resonance (H-NMR)"
        }}
      num_choices: 4
    quality_eval:
      template: |
        You are given the following spectra for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for evaluating signal quality, and generate a question, choices, and answer based on it.
        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "IR",
          "question": "Does this spectrum show obvious signal quality issues?",
          "choices": ["Yes", "No, the signal is very clear", "Localized noise", "Very low noise, negligible"],
          "answer": "No, the signal is very clear"
        }}

        Example:
        {{
          "selected_spectrum_type": "MASS",
          "question": "Does this spectrum show obvious signal quality issues?",
          "choices": ["Yes", "No, the signal is very clear", "Localized noise", "Very low noise, negligible"],
          "answer": "No, the signal is very clear"
        }}
      num_choices: 4
  question_types: ["type_cls", "quality_eval"]
model_type: internvl
model_config:
  api_key: ${INTERNVL_API_KEY}
  base_url: ${INTERNVL_BASE_URL}
  model_name: ${INTERNVL_MODEL_NAME}
  max_seq_len: 4096
num_samples: 30
output_path: output/benchmark.json
verbose: true
max_retries: 3 