dataset_path: seed_datasets/molpuzzle/meta_data.json
generator_type: benchmark
generator_config:
  prompt_templates:
    type_cls:
      template: |
        You are given the following spectra for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for the following task, and generate a question, choices, and answer based on it.
        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "IR",
          "question": "What type of spectrum is this?",
          "choices": ["Infrared Spectrum (IR)", "Proton Nuclear Magnetic Resonance (H-NMR)", "Mass Spectrometry (MS)", "Raman Spectrum"],
          "answer": "Infrared Spectrum (IR)"
        }}

        Example:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "What type of spectrum is this?",
          "choices": ["Infrared Spectrum (IR)", "Proton Nuclear Magnetic Resonance (H-NMR)", "Mass Spectrometry (MS)", "Raman Spectrum"],
          "answer": "Proton Nuclear Magnetic Resonance (H-NMR)"
        }}
      num_choices: 4
    quality_eval:
      template: |
        You are given the following spectra for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for evaluating signal quality, and generate a question, choices, and answer based on it.
        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "IR",
          "question": "Does this spectrum show obvious signal quality issues?",
          "choices": ["Yes", "No, the signal is very clear", "Localized noise", "Very low noise, negligible"],
          "answer": "No, the signal is very clear"
        }}

        Example:
        {{
          "selected_spectrum_type": "MASS",
          "question": "Does this spectrum show obvious signal quality issues?",
          "choices": ["Yes", "No, the signal is very clear", "Localized noise", "Very low noise, negligible"],
          "answer": "No, the signal is very clear"
        }}
      num_choices: 4
    feature_extract:
      template: |
        You are given the following spectrum for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for extracting characteristic features, and generate a question, choices, and answer based on it.
        Focus on extracting key features such as the position (wavenumber or ppm) of the strongest peak, the number of distinct signals, or the presence of characteristic peaks in specific regions. 

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "IR",
          "question": "Please select the approximate wavenumber of the strongest absorption peak in the image.",
          "choices": ["~1700 cm⁻¹", "~2900 cm⁻¹", "~3400 cm⁻¹", "~1100 cm⁻¹"],
          "answer": "~1700 cm⁻¹"
        }}

        Example:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "Please select the approximate ppm value of the peak within the 6-8 ppm chemical shift range in the image.",
          "choices": ["~1.2 ppm", "~3.5 ppm", "~7.1 ppm", "~9.0 ppm"],
          "answer": "~7.1 ppm"
        }}
      num_choices: 4
    impurity_detect:
      template: |
        You are given the following spectrum for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for impurity detection, and generate a question, choices, and answer based on it.
        Focus on identifying abnormal peaks, classifying them as impurity or noise, or recognizing unexpected signals that do not belong to the target compound.

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "Please observe this spectrum carefully. Besides the signals from the target compound, there is also a distinct additional peak around 2.5 ppm in the image. What is this peak most likely?",
          "choices": ["Solvent impurity", "Target compound", "Instrument noise", "Reference standard"],
          "answer": "Solvent impurity"
        }}
        Example:
        {{
          "selected_spectrum_type": "IR",
          "question": "List the wavenumbers of abnormal peaks and classify them as impurity or noise.",
          "choices": ["1720 cm⁻¹ (impurity)", "3400 cm⁻¹ (noise)", "1100 cm⁻¹ (impurity)", "None detected"],
          "answer": "1720 cm⁻¹ (impurity)"
        }}
      num_choices: 4
    group_recog:
      template: |
        You are given the following spectrum for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for functional group or fragment recognition, and generate a question, choices, and answer based on it.
        Focus on identifying the most likely functional group or chemical fragment present in the molecule, based on the spectral features.
        Do NOT generate questions about spectrum type classification, signal quality, or peak assignment.

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "IR",
          "question": "Based on this infrared spectrum, what functional group is most likely present in the molecule?",
          "choices": ["Carbonyl group (C=O)", "Hydroxyl group (-OH)", "Amino group (-NH2)", "Nitro group (-NO2)"],
          "answer": "Carbonyl group (C=O)"
        }}

        Example:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "What chemical fragment might be present in the molecule, as suggested by this spectrum?",
          "choices": ["Methyl group (-CH3)", "Phenyl group (-C6H5)", "Carboxyl group (-COOH)", "Alkene group (C=C)"],
          "answer": "Methyl group (-CH3)"
        }}
      num_choices: 4
    element_pred:
      template: |
        This is an element prediction task.

        You are provided with one or more spectrum images (such as MS, IR, NMR, etc.) for a molecule.
        Please carefully select the most appropriate spectrum type for functional group or fragment recognition, and generate a question, choices, and answer based on the information visible in the spectrum image.
        Your task is to create a question and answer that require the examinee to infer the elemental composition or isotopic pattern (for example, the presence of halogens) using the provided spectrum image.
        **Be sure to choose a spectrum type that actually has an associated image, and ensure your question is grounded in the features visible in that image.**
        Do NOT select a spectrum type that does not have an image.

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used, and ensure the "image_path" field contains the actual path to the spectrum image (it must not be empty).
        Here are some example questions for your reference. Please output your result in the following JSON format (making sure image_path points to the actual spectrum image and is not empty):

        Example 1:
        {{
          "selected_spectrum_type": "MASS",
          "question": "Given the mass spectrum image, what halogen atom is most likely present in the compound based on the observed isotopic pattern?",
          "choices": ["Fluorine (F)", "Chlorine (Cl)", "Bromine (Br)", "Iodine (I)"],
          "answer": "Chlorine (Cl)",
        }}

        Example 2:
        {{
          "selected_spectrum_type": "MASS",
          "question": "Observe the provided mass spectrum image. The M+2 peak has a significant relative intensity compared to the M peak. Which element is most likely present in the compound?",
          "choices": ["Sulfur (S)", "Bromine (Br)", "Chlorine (Cl)", "Iodine (I)"],
          "answer": "Sulfur (S)",
        }}
      num_choices: 4
    peak_assign:
      template: |
        You are given the following spectrum for a molecule:
        {spectra_list}

        Please select the most appropriate spectrum for peak assignment, and generate a question, choices, and answer based on it.
        Focus on assigning specific peaks (such as triplet, quartet, singlet, etc.) in the NMR spectrum to parts of the molecule, based on the chemical formula, SMILES, or structure.
        Do NOT generate questions about spectrum type classification, signal quality, or functional group recognition.

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "Given the chemical formula C2H6O. Observe this HNMR spectrum. The triplet peak around ~1.2 ppm in the image is most likely assigned to which part of the molecule?",
          "choices": ["-CH3 group", "-CH2 group", "-OH group", "Aromatic ring"],
          "answer": "-CH3 group"
        }}

        Example:
        {{
          "selected_spectrum_type": "C-NMR",
          "question": "Given the SMILES CC(=O)O. In this CNMR spectrum, the signal at ~180 ppm is most likely assigned to which carbon atom?",
          "choices": ["Methyl carbon", "Carboxyl carbon", "Aromatic carbon", "Alkene carbon"],
          "answer": "Carboxyl carbon"
        }}
      num_choices: 4
    property_pred:
      template: |
        This is a property prediction task.

        You are given the following spectrum(s) for a molecule:
        {spectra_list}

        You are provided with one or more spectrum images (such as MS, IR, NMR, UV-Vis, etc.) for a molecule.
        Your task is to create a question and answer that require the examinee to infer a chemical or physical property of the compound based on the features visible in the provided spectrum image(s).
        Typical properties include: molecular weight (from mass spectrum), acidity (from IR), color (from UV-Vis), solubility (from NMR), and so on.
        Please focus on designing questions that require the examinee to deduce such properties from the actual spectral features shown in the image(s).
        
        **Do not always use the mass spectrum (MS) for your question. When possible, also consider using IR, C-NMR, or H-NMR spectra to design property prediction questions, as long as the spectrum image is available and the property can be reliably inferred from it. Ensure the quality and relevance of the question.**

        **Be sure to choose a spectrum type that actually has an associated image, and ensure your question is grounded in the features visible in that image.**
        Do NOT select a spectrum type that does not have an image.

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used, and ensure the "image_path" field contains the actual path to the spectrum image (it must not be empty).

        Here are some example questions for your reference. Please output your result in the following JSON format (making sure image_path points to the actual spectrum image and is not empty):

        Example 1:
        {{
          "selected_spectrum_type": "MASS",
          "question": "Given the mass spectrum image, what is the most likely molecular ion peak (m/z) observed for this compound?",
          "choices": ["85", "90", "120", "150"],
          "answer": "120",
        }}

        Example 2:
        {{
          "selected_spectrum_type": "IR",
          "question": "Given the infrared spectrum image, a very broad absorption band in the 2500−3300 cm⁻¹ range and a strong peak around 1700 cm⁻¹ are observed. What property does this most likely suggest for the compound?",
          "choices": ["Strong acidity", "High basicity", "Aromaticity", "Aliphatic character"],
          "answer": "Strong acidity",
        }}

        Example 3:
        {{
          "selected_spectrum_type": "UV-Vis",
          "question": "Given the UV-Vis spectrum image, strong absorption is observed in the 400−500 nm wavelength range. What color does this most likely suggest for the compound?",
          "choices": ["Red", "Yellow", "Blue", "Colorless"],
          "answer": "Blue",
        }}

        Example 4:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "Based on the chemical shifts and integration in this 1H NMR spectrum image, what can you infer about the solubility of this compound in water?",
          "choices": ["Highly soluble", "Slightly soluble", "Insoluble", "Decomposes in water"],
          "answer": "Highly soluble",
        }}
      num_choices: 4
    structure_elucidate:
      template: |
        This is a structure elucidation task.

        You are given one or more spectra for an unknown molecule.
        Your goal is to deduce the most likely molecular structure (such as SMILES, 2D/3D structure, or key substructures) that is consistent with the provided spectral data.
        You may need to assemble fragments, complete partial scaffolds, or rank plausible candidate structures based on the spectra.
        Please focus on designing questions that require the examinee to infer or assemble the full or partial structure from the spectral features.

        Do NOT generate questions about simple spectrum type classification, signal quality, or single functional group recognition.

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "MASS",
          "question": "Given the mass spectrum of an unknown compound, predict the most likely molecular structure (SMILES) consistent with the observed fragments.",
          "choices": ["CCO", "c1ccccc1", "CC(=O)O", "CCN"],
          "answer": "CCO"
        }}

        Example 1:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "Given the ¹H and ¹³C NMR spectra of a compound, identify the most likely substructures present. Use this information to assemble and rank plausible candidate isomers for the full molecule.",
          "choices": ["Benzene ring", "Cyclohexane", "Ester group", "Alkyne group"],
          "answer": "Benzene ring"
        }}

        Example 2:
        {{
          "selected_spectrum_type": "MASS",
          "question": "Given multiple fragment-level features inferred from NMR and MS spectra, assemble the most likely full molecular structure by combining fragments in a chemically consistent way.",
          "choices": ["CCCO", "CCOC", "CCN", "CNC"],
          "answer": "CCCO"
        }}
      num_choices: 4
    modality_fusion:
      template: |
        This is a modality fusion task.

        You are given multiple types of information about a molecule, such as its molecular formula and one or more spectrum images (IR, NMR, MS, etc.).
        Your goal is to integrate all available information—including the provided spectrum image(s)—to infer structural features, identify functional groups, or rank candidate structures.
        When generating questions and answers, you must reference both the molecular formula and the actual spectrum image (do not ignore the image).

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "IR",
          "question": "The molecular formula of the compound is C8H8O2. Use this information together with the provided IR spectrum image to infer possible structural features.",
          "choices": ["Aromatic ring", "Alkene", "Alkyne", "Ether"],
          "answer": "Aromatic ring"
        }}

        Example 1:
        {{
          "selected_spectrum_type": "MASS",
          "question": "A compound has the formula C8H8O2. Given its mass spectrum image and 1H-NMR spectrum image, rank the following candidate structures based on how well they match the spectral data.",
          "choices": ["Structure A", "Structure B", "Structure C", "Structure D"],
          "answer": "Structure A"
        }}

        Example 2:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "Given the 1H-NMR spectrum image and the molecular formula C7H8O, what is the most likely functional group present in the molecule?",
          "choices": ["Aldehyde", "Ketone", "Alcohol", "Ether"],
          "answer": "Aldehyde"
        }}
      num_choices: 4
    mol_reasoning:
      template: |
        This is a molecular reasoning task.

        You are provided with one or more spectra (such as IR, NMR, MS, etc.) and/or other chemical information about a molecule.
        Your goal is to design questions that require logical deduction, calculation, or multi-step reasoning based on the combination of spectral and chemical data.
        Suitable questions may involve deducing molecular formulas, interpreting isotopic patterns, inferring structural features from multiple spectra, or integrating evidence from different sources to reach a conclusion.

        Please avoid generating questions that are simple spectrum type classification, direct property lookup, or only about signal quality.

        In your JSON output, include a field "selected_spectrum_type" to indicate which spectrum you used for reasoning.

        Please answer in the following JSON format:
        {{
          "selected_spectrum_type": "MASS",
          "question": "In the mass spectrum of bromohexane, two peaks of equal intensity are observed. Which of the following m/z values are most likely due to the molecular ion isotopic pattern?",
          "choices": ["15 and 29", "93 and 15", "29 and 95", "95 and 93"],
          "answer": "29 and 95"
        }}

        Example 1:
        {{
          "selected_spectrum_type": "MASS",
          "question": "A hydrocarbon with m/z = 142 was observed in the mass spectrum. What is the most likely molecular formula?",
          "choices": ["C10H22", "C11H18", "C11H10", "C8H18"],
          "answer": "C11H10"
        }}

        Example 2:
        {{
          "selected_spectrum_type": "H-NMR",
          "question": "The 1H-NMR spectrum shows a singlet at ~9.8 ppm. The IR spectrum shows a strong peak around 1700 cm⁻¹. The molecule contains a benzene ring and an unknown side group. What is the most likely functional group in the side chain?",
          "choices": ["Aldehyde", "Ketone", "Alcohol", "Amine"],
          "answer": "Aldehyde"
        }}
      num_choices: 4
  question_types: ["type_cls", "quality_eval", "feature_extract", "impurity_detect", "group_recog", "element_pred", "peak_assign", "property_pred", "structure_elucidate", "modality_fusion", "mol_reasoning"]
model_type: internvl
model_config:
  api_key: ${INTERNVL_API_KEY}
  base_url: ${INTERNVL_BASE_URL}
  model_name: ${INTERNVL_MODEL_NAME}
  max_seq_len: 4096
num_samples: 30
output_path: output/benchmark.json
verbose: true
max_retries: 3 