# CoT (Chain-of-Thought) Configuration
# Unified configuration for both text-only and multimodal CoT generation

dataset_path: SpectrumWorld/molpuzzle-seed-datasets
generator_type: cot
generator_config:
  # CoT generation settings
  cot_types: ["text_only", "multimodal"]  # Support both types
  use_claude: false
  use_internvl3: true
  image_output_dir: "output/cot_spectrum_images"
  image_format: "png"
  
  # Two-stage generation settings (configurable via command line)
  stages: ["core_generation"]  # Default: only core generation
  # Available stages: ["core_generation", "reasoning_generation"]
  
  # Stage 1: Core generation settings (for high-quality question/solution)
  core_generation:
    max_out_len: 2000
    temperature: 0.3  # Lower temperature for more focused, accurate content
    focus_quality: true
    
  # Stage 2: Reasoning generation settings (for thinking trajectories)
  reasoning_generation:
    max_out_len: 1500
    temperature: 0.7  # Higher temperature for more creative reasoning
    reasoning_models: ["claude", "internvl3"]  # Future: reasoning model selection

  # Prompt templates for different stages and CoT types
  prompt_templates:
    # Stage 1: Core generation templates (focus on high-quality question/solution)
    core_generation:
      text_only:
        template: |
          You are an expert in spectroscopic analysis and molecular structure determination. 
          Generate a high-quality reasoning problem and solution for molecular structure analysis.

          TASK: Create a detailed reasoning problem with step-by-step solution. 
          Focus on accuracy, clarity, and educational value.

          Requirements:
          - Generate a challenging but solvable spectroscopic analysis problem
          - Provide a detailed, step-by-step solution with clear explanations
          - Ensure scientific accuracy and proper terminology
          - Use the EXACT JSON format shown below

          Examples of problem types:
          - IR spectrum interpretation with functional group identification
          - NMR spectrum analysis with chemical shift assignments
          - Mass spectrometry molecular weight determination
          - Multi-spectral analysis combining different techniques
          - Complex molecular structure elucidation

          JSON Format (CORE CONTENT ONLY):
          {
            "question": "Detailed reasoning problem here...",
            "solution": "Step-by-step solution with explanations..."
          }

          Context:
          - Molecular formula: {formula}
          - SMILES: {smiles}
          - Available spectra: {available_spectra}
          - Problem type: {cot_type}

          Generate a high-quality reasoning problem in JSON format. Focus on scientific accuracy and educational value.

      multimodal:
        template: |
          You are an expert in spectroscopic analysis and molecular structure determination. 
          Analyze the provided spectrum image and generate a high-quality reasoning problem with solution.

          TASK: Create a detailed reasoning problem based on the spectrum image with step-by-step solution. 
          Focus on accuracy, clarity, and educational value.

          Requirements:
          - Analyze the provided spectrum image carefully
          - Generate a challenging but solvable spectroscopic analysis problem
          - Provide a detailed, step-by-step solution with clear explanations
          - Ensure scientific accuracy and proper terminology
          - Use the EXACT JSON format shown below

          Examples of analysis approaches:
          - Peak identification and assignment
          - Functional group analysis
          - Molecular structure elucidation
          - Quantitative analysis
          - Comparative analysis with reference spectra

          Examples of question types:
          - "What functional groups are present in this spectrum?"
          - "Identify the molecular structure from this spectrum"
          - "Explain the key features and their significance"
          - "Compare this spectrum with expected patterns"
          - "What additional information would help confirm the structure?"

          JSON Format (CORE CONTENT ONLY):
          {
            "question": "Detailed reasoning problem based on the spectrum...",
            "solution": "Step-by-step solution with explanations..."
          }

          Context:
          - Molecular formula: {formula}
          - SMILES: {smiles}
          - Available spectra: {available_spectra}
          - Problem type: {cot_type}

          Generate a high-quality reasoning problem in JSON format. Focus on scientific accuracy and educational value.

# Model configuration
model_type: internvl
model_config:
  api_key: ${INTERNVL_API_KEY}
  base_url: ${INTERNVL_BASE_URL}
  model_name: ${INTERNVL_MODEL_NAME}
  max_seq_len: 4096

# Generation settings
num_samples: 10
output_path: output/cot_data.json
verbose: true
max_retries: 3