dataset_path: SpectrumWorld/qm9s-seed-datasets-small
generator_type: cot
generator_config:
  cot_types:
  - text_only
  - multimodal
  stages:
  - draft
  - reason
  use_claude: false
  use_interns1: true
  image_output_dir: qm9s_output/cot_interns1_spectrum_images
  image_format: png
  draft:
    max_out_len: 8192
    temperature: 0.2
    focus_quality: true
  prompt_templates:
    draft:
      text_only:
        template: |
          You are an expert in spectroscopic analysis and molecular structure determination.
          Generate a high-quality reasoning problem and solution for molecular structure analysis.

          TASK: Create a detailed reasoning problem with step-by-step solution.
          Focus on accuracy, clarity, and educational value.

          Requirements:
          - Generate a challenging but solvable spectroscopic analysis problem
          - Provide a detailed, step-by-step solution with clear explanations
          - Ensure scientific accuracy and proper terminology
          - Use the EXACT JSON format shown below

          Examples of problem types:
          - IR spectrum interpretation: "Identify functional groups from IR peaks at 1700, 1600, 1250 cm⁻¹"
          - NMR analysis: "Assign chemical shifts and coupling patterns in ¹H NMR spectrum"
          - Raman spectroscopy: "Analyze Raman shifts and identify vibrational modes"
          - UV-Vis spectroscopy: "Determine conjugation and electronic transitions"
          - Mass spectrometry: "Determine molecular weight and fragmentation patterns"
          - Multi-spectral: "Combine IR, NMR, and MS data for structure elucidation"

          JSON Format (CORE CONTENT ONLY):
          {{
            "question": "Detailed reasoning problem here...",
            "solution": "Step-by-step solution with explanations..."
          }}

          Context:
          - Molecular formula: {formula}
          - SMILES: {smiles}
          - Available spectra: {available_spectra}
          - Data type: {cot_type}

          Generate a high-quality reasoning problem in JSON format. Focus on scientific accuracy and educational value.

      multimodal:
        template: |
          You are an expert in spectroscopic analysis and molecular structure determination.
          Analyze the provided {spectrum_type} spectrum image and generate a high-quality reasoning problem with solution.

          IMPORTANT: The spectrum type is {spectrum_type}. Your question and solution MUST specifically refer to this {spectrum_type} spectrum.

          TASK: Create a detailed reasoning problem based on the {spectrum_type} spectrum image with step-by-step solution.
          Focus on accuracy, clarity, and educational value.

          Requirements:
          - Analyze the provided {spectrum_type} spectrum image carefully
          - Your question MUST mention "{spectrum_type} spectrum" explicitly
          - Generate a challenging but solvable spectroscopic analysis problem
          - Provide a detailed, step-by-step solution with clear explanations
          - Ensure scientific accuracy and proper terminology
          - Use the EXACT JSON format shown below

          Examples of {spectrum_type}-specific analysis approaches:
          - Peak identification and assignment in {spectrum_type} spectroscopy
          - Functional group analysis from {spectrum_type} features
          - Molecular structure elucidation using {spectrum_type} data
          - Quantitative analysis of {spectrum_type} peaks
          - Interpretation of {spectrum_type} characteristic bands

          JSON Format (CORE CONTENT ONLY):
          {{
            "question": "Analyze the {spectrum_type} spectrum of [compound]...",
            "solution": "Step-by-step solution analyzing the {spectrum_type} spectrum..."
          }}

          Context:
          - Spectrum type: {spectrum_type} (MUST be mentioned in your question)
          - Molecular formula: {formula}
          - SMILES: {smiles}
          - Available spectra: {available_spectra}
          - Data type: {cot_type}

          Generate a high-quality reasoning problem in JSON format. Ensure your question explicitly mentions "{spectrum_type} spectrum".
  reason:
    max_out_len: 8192
    temperature: 0.7
model_type: interns1
model_config:
  api_key: ${INTERNS1_API_KEY}
  base_url: ${INTERNS1_BASE_URL}
  model_name: ${INTERNS1_MODEL_NAME}
  max_seq_len: 8192
num_samples: 1500
output_path: qm9s_output/cot_interns1_1500.json
verbose: true
max_retries: 3
